### ISSUE TITLE
Minecraft 1.18 won't build with Java 16

### ISSUE THREAD

**Issue by zaunermax** [nimmis/docker-spigot#50] opened 2021-12-02 14:18 UTC
When trying to build the newest Spigot version for MC 1.18 the container log shows this error message:

```
Found version,
{,
	"name": "3339",,
	"description": "Jenkins build 3339",,
	"refs": {,
		"BuildData": "8814411100e91e323a23a9a6355fa7d28e091054",,
		"Bukkit": "f023e77ad7343fa11812d3118efc956b67cdd242",,
		"CraftBukkit": "581df1846f2b3e09b20e71fd44851f3e68f1f7db",,
		"Spigot": "3c40a6c908b0a67b05ebf8f5268d64838e117d41",
	},,
	"toolsVersion": 138,,
	"javaVersions": [61, 61],
},
,
*** The version you have requested to build requires Java versions between [Java 17, Java 17], but you are using Java 16,
*** Please rerun BuildTools using an appropriate Java version. For obvious reasons outdated MC versions do not support Java versions that did not exist at their release.,
cp: cannot stat '/build-mc/Spigot/Spigot-Server/target/spigot-*.jar': No such file or directory,
*** Running /etc/my_runalways/85_fix_startsh...,
*** Running /etc/my_runalways/90_eula...,
*** Booting supervisor daemon...,
*** Supervisor started as PID 146,
*** Started processes via Supervisor......,
crond                            RUNNING   pid 148, uptime 0:00:04,
spigot                           BACKOFF   Exited too quickly (process log may have details),
syslog-ng                        RUNNING   pid 150, uptime 0:00:04
```

**Comment by nimmis** [comment] 2021-12-02 14:23
I Know, working on a new release that can handle both 1.18 and previous versions of minecraft. You cannot use java 1.17 to build older versions of mc. It will be released today or tomorrow because I need to redesigen/add new code to handel legacy versions.

**Comment by ginomessmer** [comment] 2021-12-07 20:49
@nimmis Sounds good. Any way we could help?

**Comment by nimmis** [comment] 2021-12-08 05:50
@ginomessmer All the coding is done, just checking that all logic does work as intended and updating the documentation as there are allot of changes/improvements. I do this on my spare time with other commitments some delays can happen, but if nothing really bad is found I will release it today.

**Comment by nimmis** [comment] 2021-12-08 09:30
@ginomessmer @zaunermax released
Don't forget to do a

    docker pull nimmis/spigot

before to update version

**Closed by nimmis** 2021-12-08 09:30 UTC
Labels: bug
